#-------------------------------------------------------------------------------
#
#     qpipe library build construction script
#
import os

#-------------------------------------------------------------------------------
#
#     General
#
Import('env')

env = env.Clone()
Platform = env['PLATFORM']

#-------------------------------------------------------------------------------
#
#     Setup sources and target
#
Sources = [ 'shared_mem.cpp',
            'ip_qpipe.cpp',
            'ip_qpipe_lib.cpp',
            'ip_qpipe.h',
            'shared_mem.h' ] #,
#           '../../../include/ip_qpipe_def.h',
#           '../../../include/ip_qpipe_lib.h',
#           '../../../include/tqueue.h' ]

Target  = os.path.join(env['LIBPATH'], env['PRODUCT_NAME'])

#-------------------------------------------------------------------------------
#
#     Setup local construction environment
#
env.EnableQt5Modules(['QtTest', 'QtNetwork'])

DEFINES = ['ENA_FW_QT']

if Platform == 'win32':
    DEFINES += ['ENA_WIN_API']

env.Append(CCFLAGS = ['-D'+ d for d in DEFINES] )

#-------------------------------------------------------------------------------
#
#     Build the target
#
lib = env.StaticLibrary(Target, Sources)

#-------------------------------------------------------------------------------

